dist: trusty
language: php

php:
  - 7.4
  - 8.1
  - 8.2

before_install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install --yes nodejs
  - npm install -g grunt-cli

install:
  - npm install
  - composer install

script:
  - grunt

after_script:
  - php vendor/bin/coveralls -v
